### ISSUE TITLE
ghidra 16 hex digit externals kill

### ISSUE THREAD

**Issue by barrybingo** [utkonos/lst2x64dbg#2]
From a ghidra dump I had external symbols over 8 hex digits long that caused your program to crash.
The addresses for External seem to be either 8 or 16 hex digits.

e.g.:  External[8000000000000097]

https://github.com/utkonos/lst2x64dbg/blob/780acf20abaf2e3e4d7b14d1acf8b65623d38603/lst2x64dbg/command_line.py#L177

**Comment by utkonos** [comment]
Fixed. Thanks for the report!
