### ISSUE TITLE
x32dbg does not show .dd32 symbols in the disassembly listing 

### ISSUE THREAD

**Issue by glaukon-ariston** [utkonos/lst2x64dbg#3]
I converted Ghidra's CSV file to the `dd32` file with your `ghidra2x64dbg` tool. I then imported the `dd32` database into x32dbg (`File | Import Database`). I can see the loaded symbols in the `References | Labels` tab (when I select `View | Lables`), but I don't see them referenced in the disassembly listing (CPU tab).

**Comment by utkonos** [comment]
@glaukon-ariston Thanks for reporting this issue. Can you provide the CSV file as well as the command line you used to convert it so I can test and reproduce the issue?

**Comment by utkonos** [comment]
Closing this issue. If you have the CSV that produced the problem so I can test and fix, please upload it.
